### ISSUE TITLE
system-config-samba broken: Lib´s wget Not Found anymore, not installing on ubuntu 21.04

### ISSUE THREAD

**Issue by rpotalara** [zpangwin/linux-setup-scripts#1]
Hi @zpangwin , thank´s for this script but I try to use and Lib´s in wget can´t be find anymore. Not Found. Can you help? Thank´s

I found in:
http://mirrors.kernel.org/ubuntu/pool/universe/p/pygtk/python-gtk2_2.24.0-5.1ubuntu2_amd64.deb
http://old.kali.org/kali/pool/main/p/pygtk/python-glade2_2.24.0-6_amd64.deb
http://mirrors.kernel.org/ubuntu/pool/universe/libu/libuser/python-libuser_0.62~dfsg-0.1ubuntu2_i386.deb
http://mirror.internode.on.net/pub/ubuntu/ubuntu/pool/universe/libu/libuser/python-libuser_0.62~dfsg-0.1ubuntu2_amd64.deb
http://mirrors.kernel.org/ubuntu/pool/universe/s/system-config-samba/system-config-samba_1.2.63-0ubuntu6_all.deb

**Comment by zpangwin** [comment]
Thanks for the report. Sounds like you're interested in the setup scripts for my `system-config-samba` for Mint 20 / Ubuntu 20.04.

I'm seeing that my scripts in this repo are a bit behind my local copies (I currently am pulling them from my other repo which is a superset of these changes.. I probably need to consider revising this structure). I'll look into merging new copies into my github/gitlab repos soon.

In the mean time, I checked the lastest script I have for this and am able to confirm that 2 of the links appear broken for me as well (python0gtk and python glade).

    $ grep wget install-system-config-samba-config.sh 
    wget http://archive.ubuntu.com/ubuntu/pool/universe/p/pygtk/python-gtk2_2.24.0-6_amd64.deb
    wget http://archive.ubuntu.com/ubuntu/pool/universe/p/pygtk/python-glade2_2.24.0-6_amd64.deb
    wget http://archive.ubuntu.com/ubuntu/pool/universe/libu/libuser/python-libuser_0.62~dfsg-0.1ubuntu2_amd64.deb
    wget http://archive.ubuntu.com/ubuntu/pool/universe/s/system-config-samba/system-config-samba_1.2.63-0ubuntu6_all.deb
     
    $ mkdir /tmp/DgZk/ && cd $_
    $ wget http://archive.ubuntu.com/ubuntu/pool/universe/p/pygtk/python-gtk2_2.24.0-6_amd64.deb 2>&1|grep '404'
    HTTP request sent, awaiting response... 404 Not Found
    2021-05-06 13:38:25 ERROR 404: Not Found.
     
    $ wget http://archive.ubuntu.com/ubuntu/pool/universe/p/pygtk/python-glade2_2.24.0-6_amd64.deb 2>&1|grep 404
    HTTP request sent, awaiting response... 404 Not Found
    2021-05-06 13:39:06 ERROR 404: Not Found.

The deb files for `python-libuser_0.62~dfsg-0.1ubuntu2_amd64.deb` and `system-config-samba_1.2.63-0ubuntu6_all.deb` seemed to still work ok for me. I am able to view theirs contants with file roller too so doesn't look like they are zero-byte files.

    $ sha256 *
    bd3ecca23fa389d2eb1a21d18408a4ce4f2e80aee4613534c96b8b7a987e37f8  python-libuser_0.62~dfsg-0.1ubuntu2_amd64.deb
    a07e97bd20a7904984e99be2dcafd484e5b498ff8656043aefee95d728bf1daf  system-config-samba_1.2.63-0ubuntu6_all.deb


I'll need to investigate some more but I would expect there to still be links for these archives for some time yet. The last I checked, `system-config-samba` worked fine and was available from central repos in Mint 19.3 and Ubuntu 18.04. According to [Ubuntu's own wiki](https://wiki.ubuntu.com/Releases), 18.04 should still be supported until April 2023 and End of Life not occurring until April 2028. In other words, I would think the files ought to be available somewhere because many of them are actively used in Ubuntu 18.04 installs.

**Comment by zpangwin** [comment]
I see that when accessing [http://archive.ubuntu.com/ubuntu/pool/universe/p/pygtk](http://archive.ubuntu.com/ubuntu/pool/universe/p/pygtk) in firefox that there are still some files in there but they appear to be a minor version behind (`python-gtk2_2.24.0-5.1ubuntu2_amd64.deb` instead of `python-gtk2_2.24.0-6_amd64.deb` and `python-glade2_2.24.0-5.1ubuntu2_amd64.deb` instead of `python-glade2_2.24.0-6_amd64.deb`) so not sure what happened.

    $ wget http://archive.ubuntu.com/ubuntu/pool/universe/p/pygtk/python-gtk2_2.24.0-5.1ubuntu2_amd64.deb
    $ wget http://archive.ubuntu.com/ubuntu/pool/universe/p/pygtk/python-glade2_2.24.0-5.1ubuntu2_amd64.deb
    $ sha256 *2.24.0-5*.deb
    08770619ea16aa0b68b4522cf5694d51d9fe08866de9d8f28d7c188bfd78345e  python-glade2_2.24.0-5.1ubuntu2_amd64.deb
    255d1b10fa52e4551eb330375e1a3324b9b9220d3242281e9cb3a60dc8b13b50  python-gtk2_2.24.0-5.1ubuntu2_amd64.deb

I am able to download them without any errors using wget. But am not currently on an Ubuntu-based system right now to be able to test so I'll have to check later whether these work as replacements or not.

**Comment by rpotalara** [comment]
Hi @zpangwin , thank´s for reply, I'm actually using the version Ubuntu Server 21.04 and I've been away from Linux for a long time, so I looked for ease and found your script.

**Comment by zpangwin** [comment]
Ok, I have a box running LM20 (Ubuntu 20 base) that doesn't have `system-config-samba` installed yet. When I get time, I might try this over on that box first since I can run directly without needing to download iso and setup VM. If I'm able to get it working, I'll post back with steps I used and you can test if that works for 21.04 as well. If not, then I can look at the VM route.

**Comment by zpangwin** [comment]
Ok, got some time to test things out on my Mint 20 box today and here's what I found.

1\. The above `python*2.24.0-5.1ubuntu2_amd64.deb` versions *did* seem to work as replacements. While running I did get the following error output:

    sudo apt-get install -y ./*.deb
    ...
    N: Download is performed unsandboxed as root as file '/tmp/hc6/python-gtk2_2.24.0-5.1ubuntu2_amd64.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)

but after applying the remaining system-config-samba workarounds (mentioned [here](https://askubuntu.com/questions/1136341/what-happened-to-system-config-samba-in-19-04/1256954#1256954)), I was able to get the gui to come up without any issues.

2\. After checking my notes to see if there were other mirrors for the newer versions, I saw one of the [answers that mine was based on](https://askubuntu.com/questions/1233710/where-is-fslint-duplicate-file-finder-for-ubuntu-20-04/1233818#1233818) had been updated to include some alternate mirrors for Ubuntu 20.10. I decided to remove everything from the first test (`sudo apt-get purge -y system-config-samba python-libuser python-gtk2 python-glade2`) and try with this approach as well.

    # per the fslint post, additional depends are needed on Ubuntu 20.10+
    wget http://archive.ubuntu.com/ubuntu/pool/main/libf/libffi/libffi7_3.3-4_amd64.deb
    wget http://archive.ubuntu.com/ubuntu/pool/universe/p/pygobject-2/python-gobject-2_2.28.6-14ubuntu1_amd64.deb
    wget http://archive.ubuntu.com/ubuntu/pool/universe/p/pycairo/python-cairo_1.16.2-2ubuntu2_amd64.deb
     
    # plus the original deb files we needed back on Ubuntu 19.10+
    wget http://old-releases.ubuntu.com/ubuntu/pool/universe/p/pygtk/python-gtk2_2.24.0-6_amd64.deb
    wget http://old-releases.ubuntu.com/ubuntu/pool/universe/p/pygtk/python-glade2_2.24.0-6_amd64.deb
    wget http://archive.ubuntu.com/ubuntu/pool/universe/libu/libuser/python-libuser_0.62~dfsg-0.1ubuntu2_amd64.deb
    wget http://archive.ubuntu.com/ubuntu/pool/universe/s/system-config-samba/system-config-samba_1.2.63-0ubuntu6_all.deb

For newer versions of Ubuntu, you may need to run `dpkg -I package.deb` (as shown [here](https://askubuntu.com/questions/80655/how-can-i-check-dependency-list-for-a-deb-package)) to determine if additional dependencies have been removed beyond those that were removed back in versions 19.10-20.04, which seems to be the implication from the fslint post (e.g. it looks like python-gtk2 depends on libcairo2 which *is* present under Mint 20 / Ubuntu 20.04 but it sounds like it is *not* present under Ubuntu 20.10+).

Here is what I was seeing under Mint 20:

    $ dpkg-deb -I system-config-samba_1.2.63-0ubuntu6_all.deb | grep -i depend
     Depends: python, python:any (>= 2.7.5-5~), samba, python-libuser, python-glade2
     
    $ dpkg-deb -I python-libuser_0.62~dfsg-0.1ubuntu2_amd64.deb | grep -i depend
     Depends: python (<< 2.8), python (>= 2.7~), python:any (<< 2.8), python:any (>= 2.7~), libc6 (>= 2.4), libglib2.0-0 (>= 2.24.0), libuser1 (>= 1:0.60~dfsg)
     
    $ dpkg-deb -I python-gtk2_2.24.0-6_amd64.deb | grep -i depend
     Depends: python (<< 2.8), python (>= 2.7), python:any (>= 2.6.6-7~), libatk1.0-0 (>= 1.12.4), libc6 (>= 2.28), libcairo2 (>= 1.2.4), libgdk-pixbuf2.0-0 (>= 2.22.0), libglib2.0-0 (>= 2.24.0), libgtk2.0-0 (>= 2.24.0), libpango-1.0-0 (>= 1.22.0), libpangocairo-1.0-0 (>= 1.21.4), python-cairo (>= 1.0.2-1.1), python-gobject-2 (>= 2.21.3)
    
    $ dpkg-deb -I python-glade2_2.24.0-6_amd64.deb | grep -i depend
     Depends: python (<< 2.8), python (>= 2.7), libc6 (>= 2.4), libglade2-0 (>= 1:2.6.4-2~), libglib2.0-0 (>= 2.12.0), libgtk2.0-0 (>= 2.18.0), python-gtk2 (= 2.24.0-6)

When installing this way, just as with the first approach I got a non-blocking error in terminal output during install but was able to run system-config-samba afterwards without issue.

    $ sudo apt-get install -y ./*.deb
    ...
    N: Download is performed unsandboxed as root as file '/tmp/myW/python-gtk2_2.24.0-6_amd64.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)

**Comment by zpangwin** [comment]
I'll have to setup a VM to see if this works under 21.04. Probably won't be able to get to it for a couple days so if you feel like testing to see if the above works or not, the please let me know what you find (friendly reminder: don't forget to make a timeshift/etc backup first!!!).

In the mean time, I pushed an update to my Mint 20 [install script](https://github.com/zpangwin/linux-setup-scripts/tree/master/mint-20/deprecated-system-config-samba) that should at least address this issue up thru Mint 20 / Ubuntu 20.04 (and hopefully for Ubuntu 20.10 as well). Not clear yet if additional depends are needed for 21.04 yet tho.

**Comment by rpotalara** [comment]
Hy @zpangwin , I am still with some errors to use but i am able to open system-config-samba. I will try with version  20.04

**Comment by zpangwin** [comment]
Sorry for the lack of updates... ran into some issues with Ubuntu in virtualbox and didn't have as much time to tinker with it as I originally thought. Install had gone ok other than taking forever to finish but Ubuntu 21 seemed to keep getting stuck on the splash screen / the black screen after it (or maybe I was being too impatient?).  

Apparently, Virtualbox defaults to giving the guest 1 core but I didn't realize this until just now. Anyway, giving it more cores fixed it and let me boot to the welcome screen/log in. Since I had 8 cores on the host and don't generally run multiple VMs at the same time / this was just a temp project, I went ahead and gave it 4 cores and that seemed to let me get to the welcome screen within a reasonable amount of time. After that, I went ahead and installed system updates and vbox guest addons. Don't think this will be too relevant for you but you never know -- and since I don't play with VMs often, if I run into similar issues with Ubuntu 22/etc, this little reminder might help me later :-)

Will try to look at this some more soon now that I have the VM working

**Comment by zpangwin** [comment]
Just tested the steps manually using the updated deb file urls I posted last time. Seems to be working for me in virtualbox. Note that if you don't do the [other workarounds](https://askubuntu.com/questions/1136341/what-happened-to-system-config-samba-in-19-04/1256954#1256954) to fix all the other problems with this old package, that it will fail to launch even if you have installed it correctly. For the polkit workaround, since it didn't have a default config I opted to be lazy and use the one from my repo but doing it manually with vim/nano/gedit/whatever should be fine too. I didn't really test it beyond just confirming it comes up.

![system-config-samba-in-ubuntu-21 04](https://user-images.githubusercontent.com/29719631/119404144-ecf9a280-bcce-11eb-853d-6501bace5990.png)

    # TEMP DIR
    $ tempDir=$(mktemp -d /tmp/XXX);cd ${tempDir}
     
    # DOWNLOADS
    wget -q http://archive.ubuntu.com/ubuntu/pool/main/libf/libffi/libffi7_3.3-4_amd64.deb
    wget -q http://archive.ubuntu.com/ubuntu/pool/universe/p/pygobject-2/python-gobject-2_2.28.6-14ubuntu1_amd64.deb
    wget -q http://archive.ubuntu.com/ubuntu/pool/universe/p/pycairo/python-cairo_1.16.2-2ubuntu2_amd64.deb
    wget -q http://old-releases.ubuntu.com/ubuntu/pool/universe/p/pygtk/python-gtk2_2.24.0-6_amd64.deb
    wget -q http://old-releases.ubuntu.com/ubuntu/pool/universe/p/pygtk/python-glade2_2.24.0-6_amd64.deb
    wget -q http://archive.ubuntu.com/ubuntu/pool/universe/libu/libuser/python-libuser_0.62~dfsg-0.1ubuntu2_amd64.deb
    wget -q http://archive.ubuntu.com/ubuntu/pool/universe/s/system-config-samba/system-config-samba_1.2.63-0ubuntu6_all.deb
     
    # REFERENCE: YOU CAN SKIP THIS / USE IT TO VERIFY SIZES
    $ ls -acl
    total 1156
    drwx------  2 demo demo   4096 May 24 15:56 .
    drwxrwxrwt 20 root root   4096 May 24 15:45 ..
    -rw-rw-r--  1 demo demo  19688 May 24 15:56 libffi7_3.3-4_amd64.deb
    -rw-rw-r--  1 demo demo  57148 May 24 15:56 python-cairo_1.16.2-2ubuntu2_amd64.deb
    -rw-rw-r--  1 demo demo   8984 May 24 15:56 python-glade2_2.24.0-6_amd64.deb
    -rw-rw-r--  1 demo demo 181516 May 24 15:56 python-gobject-2_2.28.6-14ubuntu1_amd64.deb
    -rw-rw-r--  1 demo demo 616904 May 24 15:56 python-gtk2_2.24.0-6_amd64.deb
    -rw-rw-r--  1 demo demo  16138 May 24 15:56 python-libuser_0.62~dfsg-0.1ubuntu2_amd64.deb
    -rw-rw-r--  1 demo demo 265630 May 24 15:56 system-config-samba_1.2.63-0ubuntu6_all.deb
     
    # REFERENCE: YOU CAN SKIP THIS / USE IT TO VERIFY CHECKSUMS
    $ sha256sum *.deb
    4584aa8fef1bf5086168ce2f7078cd2ebd78fdc4cc0d86d958d795d4e0b0f50d  libffi7_3.3-4_amd64.deb
    2c953cfab659482f1d4ced08873956c79768a74785364aa97fee24f1654bceda  python-cairo_1.16.2-2ubuntu2_amd64.deb
    41c7f1c3237854b1e69a16873a845001adc3d2d610b29b016e24fcc57f1955d1  python-glade2_2.24.0-6_amd64.deb
    ecd489f03797ffe85ebb34ae9dd1d833dbe584a54524c29977dc180ea4eebbbb  python-gobject-2_2.28.6-14ubuntu1_amd64.deb
    99efe128583941807a667a16d5dcf49b652ae83b03ada620b68d20a8cff90dcd  python-gtk2_2.24.0-6_amd64.deb
    bd3ecca23fa389d2eb1a21d18408a4ce4f2e80aee4613534c96b8b7a987e37f8  python-libuser_0.62~dfsg-0.1ubuntu2_amd64.deb
    a07e97bd20a7904984e99be2dcafd484e5b498ff8656043aefee95d728bf1daf  system-config-samba_1.2.63-0ubuntu6_all.deb
     
    # REFERENCE: YOU CAN SKIP THIS / USE IT TO MANUALLY VERIFY DEPENDS
    $ for f in *.deb; do printf 'f: %s, %s\n\n' "$f" "$(dpkg-deb -I "$f" | grep -i depend)"; done
    \f: libffi7_3.3-4_amd64.deb,  Depends: libc6 (>= 2.14)
     
    f: python-cairo_1.16.2-2ubuntu2_amd64.deb,  Depends: python2 (<< 2.8), python2 (>= 2.7~), python2:any (<< 2.8), python2:any (>= 2.7~), libc6 (>= 2.14), libcairo2 (>= 1.14.0)
     
    f: python-glade2_2.24.0-6_amd64.deb,  Depends: python (<< 2.8), python (>= 2.7), libc6 (>= 2.4), libglade2-0 (>= 1:2.6.4-2~), libglib2.0-0 (>= 2.12.0), libgtk2.0-0 (>= 2.18.0), python-gtk2 (= 2.24.0-6)
     
    f: python-gobject-2_2.28.6-14ubuntu1_amd64.deb,  Depends: python2 (<< 2.8), python2 (>= 2.7~), python2:any (<< 2.8), python2:any (>= 2.7~), libc6 (>= 2.14), libffi7 (>= 3.3~20180313), libglib2.0-0 (>= 2.41.1)
     
    f: python-gtk2_2.24.0-6_amd64.deb,  Depends: python (<< 2.8), python (>= 2.7), python:any (>= 2.6.6-7~), libatk1.0-0 (>= 1.12.4), libc6 (>= 2.28), libcairo2 (>= 1.2.4), libgdk-pixbuf2.0-0 (>= 2.22.0), libglib2.0-0 (>= 2.24.0), libgtk2.0-0 (>= 2.24.0), libpango-1.0-0 (>= 1.22.0), libpangocairo-1.0-0 (>= 1.21.4), python-cairo (>= 1.0.2-1.1), python-gobject-2 (>= 2.21.3)
     
    f: python-libuser_0.62~dfsg-0.1ubuntu2_amd64.deb,  Depends: python (<< 2.8), python (>= 2.7~), python:any (<< 2.8), python:any (>= 2.7~), libc6 (>= 2.4), libglib2.0-0 (>= 2.24.0), libuser1 (>= 1:0.60~dfsg)
     
    f: system-config-samba_1.2.63-0ubuntu6_all.deb,  Depends: python, python:any (>= 2.7.5-5~), samba, python-libuser, python-glade2
     
    # INSTALL:
    # Note I got a couple warnings about:
    #	'Failed to preset unit' and
    # 	'N: Download is performed unsandboxed as root as file'
    # I just ignored these and they didn't seem to matter for the purpose of getting SCS running
    sudo apt-get install -y ./*.deb
     
    # TEST: DID INSTALL WORK?
    which system-config-samba
    /usr/sbin/system-config-samba
     
    # WORKAROUND #1
    sudo touch /etc/libuser.conf
     
    # WORKAROUND #2
    grep Exec /usr/share/applications/system-config-samba.desktop
    Exec=gksu system-config-samba
     
    sudo sed -Ei 's|^Exec=.*$|Exec=/usr/bin/pkexec --user root /usr/sbin/system-config-samba|g' /usr/share/applications/system-config-samba.desktop
     
    # WORKAROUND #3
    $ cat /usr/share/polkit-1/actions/org.freedesktop.policykit.pkexec.policy
    cat: /usr/share/polkit-1/actions/org.freedesktop.policykit.pkexec.policy: No such file or directory
     
    $  wget -q https://raw.githubusercontent.com/zpangwin/linux-setup-scripts/master/mint-20/deprecated-system-config-samba/usr/share/polkit-1/actions/org.freedesktop.policykit.pkexec.policy
     
    $ sudo cp org.freedesktop.policykit.pkexec.policy /usr/share/polkit-1/actions/org.freedesktop.policykit.pkexec.policy
    demo@vbox:/tmp/9UN$ sudo chown root:root /usr/share/polkit-1/actions/org.freedesktop.policykit.pkexec.policy
    demo@vbox:/tmp/9UN$ sudo chmod 644 /usr/share/polkit-1/actions/org.freedesktop.policykit.pkexec.policy
    demo@vbox:/tmp/9UN$ ls -acl /usr/share/polkit-1/actions/org.freedesktop.policykit.pkexec.policy
    -rw-r--r-- 1 root root 771 May 24 16:13 /usr/share/polkit-1/actions/org.freedesktop.policykit.pkexec.policy
     
    # At this point I clicked on the "App-drawer" / "Start" button thing in the lower left of the screen
    # then searched for "samba" and clicked it.
    # It (correctly) prompted for user password - note that this will fail if user in not in sudoers list.
    # After entering password, it came up no problem, as shown in screenshot.

**Comment by rpotalara** [comment]
Hi @zpangwin , thank´s so much, I will try to test again with all workaround´s

**Comment by zpangwin** [comment]
> Hi @zpangwin , thank´s so much, I will try to test again with all workaround´s

Sounds good. If you run into any issues, please capture terminal errors and I'll take a look but I think it should work.
